[user]
username="henrik3" # valorant username
tag="euw3" # valorant tag
region="eu" # one of ["eu", "na", "latam", "br", "ap", "kr"]; optional, defaults to "eu"
platform="pc" # of of ["pc", "console"]; optional, defaults to "pc"

[auth]
key="" # api key; see https://docs.henrikdev.xyz/authentication-and-authorization on how to get your own

[display]
template="w/l - {w}/{l}" # template string; accepted literals are ["{w}", "{l}", "{season}", "{change}", "{rr}", "{rank}"]
file_path="" # file output path; -> This is the file you put as your obs source

[internal]
interval=120 # value in seconds to wait between api calls (keep this reasonable, even though the basic api key supports 30req/min); optional, defaults to 120 seconds
